# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cameron Abplanalp
title_separator: "|"
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Cameron Abplanalp, Senior at the University of Wisconsin-Madison graduating in Spring 2024.
locale: en-US
url: "https://cjabplanalp.github.io"
# baseurl: "/home/" # see https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
github_username: cjabplanalp
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Cameron Abplanalp"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "DS & iSci & CS @ UW-Madison '24"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://cjabplanalp.github.io/"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cjabplanalp"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/cjabplanalp/"
    - label: "Resume"
      icon: "fas fa-fw fa-link"
      url: "https://cjabplanalp.github.io/assets/files/abplanalp_resume.pdf"

footer:
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cjabplanalp"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/cjabplanalp/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
